### ISSUE TITLE
Fix Challenges

### ISSUE THREAD

**Issue by AidanCooper2003** [Konoca/Co-Op_HUD_plus#47]
Whenever a co-op player joins in a challenge, it reverts the UI back to the original. I've tested this on the following challenges:
Head Trauma (Completed full run), Pitch Black, and Suicide King. I also tried it on Backasswards, and that was the only one I tested that worked. My best guess for the source of the issue is that in challenges the coop players don't have to select a character.

**Comment by Konoca** [comment]
Your guess was right, the mod was waiting for the joining player to either select a character or hit the back button which isn't needed in challenges.
